In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
df=pd.read_csv("dataset.csv")
df

0         1         2         3         4         5         6  \
0    0.568627  0.572549  0.580392  0.588235  0.596078  0.592157  0.600000   
1    0.552941  0.556863  0.564706  0.560784  0.568627  0.580392  0.580392   
2    0.572549  0.584314  0.592157  0.596078  0.603922  0.603922  0.619608   
3    0.584314  0.592157  0.600000  0.603922  0.615686  0.635294  0.631373   
4    0.584314  0.588235  0.600000  0.603922  0.611765  0.627451  0.639216   
..        ...       ...       ...       ...       ...       ...       ...   
395  0.690196  0.545098  0.666667  0.698039  0.725490  0.721569  0.717647   
396  0.690196  0.686275  0.729412  0.741176  0.725490  0.733333  0.725490   
397  0.552941  0.745098  0.737255  0.752941  0.752941  0.749020  0.760784   
398  0.686275  0.737255  0.768627  0.784314  0.764706  0.768627  0.764706   
399  0.709804  0.749020  0.768627  0.784314  0.764706  0.780392  0.768627   

            7         8         9  ...       775       776       777  \
0    0.596078  0.607843  0.615686  ...  0.662745  0.670588  0.666667   
1    0.580392  0.588235  0.600000  ...  0.580392  0.596078  0.584314   
2    0.619608  0.623529  0.627451  ...  0.678431  0.686275  0.686275   
3    0.639216  0.643137  0.650980  ...  0.694118  0.686275  0.686275   
4    0.639216  0.647059  0.650980  ...  0.686275  0.686275  0.686275   
..        ...       ...       ...  ...       ...       ...       ...   
395  0.721569  0.713725  0.705882  ...  0.733333  0.725490  0.729412   
396  0.721569  0.741176  0.737255  ...  0.737255  0.737255  0.745098   
397  0.752941  0.756863  0.756863  ...  0.756863  0.756863  0.760784   
398  0.784314  0.760784  0.776471  ...  0.760784  0.768627  0.756863   
399  0.772549  0.768627  0.764706  ...  0.788235  0.768627  0.776471   

          778       779       780       781       782       783  784  
0    0.662745  0.658824  0.658824  0.662745  0.662745  0.658824  0.0  
1    0.588235  0.588235  0.588235  0.580392  0.588235  0.592157  0.0  
2    0.682353  0.682353  0.678431  0.678431  0.678431  0.674510  0.0  
3    0.690196  0.686275  0.682353  0.686275  0.682353  0.678431  0.0  
4    0.686275  0.686275  0.682353  0.686275  0.686275  0.682353  0.0  
..        ...       ...       ...       ...       ...       ...  ...  
395  0.721569  0.737255  0.729412  0.733333  0.721569  0.749020  1.0  
396  0.737255  0.749020  0.733333  0.741176  0.745098  0.733333  1.0  
397  0.752941  0.741176  0.745098  0.752941  0.760784  0.749020  1.0  
398  0.768627  0.768627  0.760784  0.749020  0.752941  0.760784  1.0  
399  0.760784  0.780392  0.772549  0.768627  0.760784  0.764706  1.0  

[400 rows x 785 columns]

In [2]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
X_train, X_test, Y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [3]:
model = SVC(kernel='linear')
model.fit(X_train, Y_train)

SVC(kernel='linear')

In [4]:
y_pred = model.predict(X_test)
y_pred

array([0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
       0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.])

In [5]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.6625


In [6]:
from sklearn.metrics import confusion_matrix
m=confusion_matrix(y_test,y_pred)
m

array([[32, 11],
       [16, 21]], dtype=int64)

In [7]:
from sklearn.metrics import confusion_matrix
def sensitivity(y_test, y_pred):
    tp, fn, fp, tn = confusion_matrix(y_test, y_pred).ravel()
    return tp / (tp + fn)
def specificity(y_test, y_pred):
    tp, fn, fp, tn = confusion_matrix(y_test, y_pred).ravel()
    return tn / (tn + fp)
def presicion(y_test, y_pred):
    tp, fn, fp, tn = confusion_matrix(y_test, y_pred).ravel()
    return tp / (tp + fp)
def balanced_accuracy(y_test, y_pred):
    return (specificity+sensitivity)/2

In [8]:
sensitivity = sensitivity(y_test, y_pred)
print(sensitivity)
specificity=specificity(y_test, y_pred)
print(specificity)
presicion=presicion(y_test, y_pred)
print(presicion)
balanced_accuracy=balanced_accuracy(y_test, y_pred)
print(balanced_accuracy)

0.7441860465116279
0.5675675675675675
0.6666666666666666
0.6558768070395977


In [9]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, balanced_accuracy_score, confusion_matrix

model = SVC(kernel='linear')

skf = StratifiedKFold(n_splits=10)
scores = []
precisions = []
specificities = []
sensitivities = []
recalls = []
balanced_accuracies = []
f1_scores = []
confusion_matrices = []

for k, (train_index, test_index) in enumerate(skf.split(X_train, Y_train)):
    X_train_fold, X_test_fold = X_train.iloc[train_index], X_train.iloc[test_index]
    Y_train_fold, Y_test_fold = Y_train.iloc[train_index], Y_train.iloc[test_index]
    
    model.fit(X_train_fold, Y_train_fold)
    y_pred = model.predict(X_test_fold)
    
    score = accuracy_score(Y_test_fold, y_pred)
    precision = precision_score(Y_test_fold, y_pred)
    recall = recall_score(Y_test_fold, y_pred)
    balanced_accuracy = balanced_accuracy_score(Y_test_fold, y_pred)
    f1 = f1_score(Y_test_fold, y_pred)
    confusion = confusion_matrix(Y_test_fold, y_pred)
    
    scores.append(score)
    precisions.append(precision)
    recalls.append(recall)
    balanced_accuracies.append(balanced_accuracy)
    f1_scores.append(f1)
    confusion_matrices.append(confusion)
    
    tn, fp, fn, tp = confusion.ravel()
    specificity = tn / (tn + fp)
    specificities.append(specificity)
    sensitivity = tp / (tp + fn)
    sensitivities.append(sensitivity)

    print('Fold: %2d' % (k+1))
    print('Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
        score, precision, specificity, sensitivity, recall))
    print('Balanced Accuracy: %.3f, F1 Score: %.3f' % (balanced_accuracy, f1))
    print('Confusion Matrix:\n', confusion)
    print('\n')

mean_score = np.mean(scores)
mean_precision = np.mean(precisions)
mean_recall = np.mean(recalls)
mean_balanced_accuracy = np.mean(balanced_accuracies)
mean_f1 = np.mean(f1_scores)
mean_specificity = np.mean(specificities)
mean_sensitivity = np.mean(sensitivities)
mean_confusion = np.mean(confusion_matrices, axis=0)

print('Mean Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
    mean_score, mean_precision, mean_specificity, mean_sensitivity, mean_recall))
print('Mean Balanced Accuracy: %.3f, F1 Score: %.3f' % (mean_balanced_accuracy, mean_f1))
print('Mean Confusion Matrix:\n', mean_confusion)
print('\n\nCross-Validation Accuracy: %.3f +/- %.3f' % (np.mean(scores), np.std(scores)))

Fold:  1
Accuracy: 0.625, Precision: 0.650, Specificity: 0.500, Sensitivity: 0.722, Recall: 0.722
Balanced Accuracy: 0.611, F1 Score: 0.684
Confusion Matrix:
 [[ 7  7]
 [ 5 13]]


Fold:  2
Accuracy: 0.625, Precision: 0.688, Specificity: 0.643, Sensitivity: 0.611, Recall: 0.611
Balanced Accuracy: 0.627, F1 Score: 0.647
Confusion Matrix:
 [[ 9  5]
 [ 7 11]]


Fold:  3
Accuracy: 0.750, Precision: 0.778, Specificity: 0.714, Sensitivity: 0.778, Recall: 0.778
Balanced Accuracy: 0.746, F1 Score: 0.778
Confusion Matrix:
 [[10  4]
 [ 4 14]]


Fold:  4
Accuracy: 0.750, Precision: 0.714, Specificity: 0.600, Sensitivity: 0.882, Recall: 0.882
Balanced Accuracy: 0.741, F1 Score: 0.789
Confusion Matrix:
 [[ 9  6]
 [ 2 15]]


Fold:  5
Accuracy: 0.656, Precision: 0.667, Specificity: 0.600, Sensitivity: 0.706, Recall: 0.706
Balanced Accuracy: 0.653, F1 Score: 0.686
Confusion Matrix:
 [[ 9  6]
 [ 5 12]]


Fold:  6
Accuracy: 0.531, Precision: 0.571, Specificity: 0.600, Sensitivity: 0.471, Recall: 0.471
Ba

# Using test data

In [10]:
dfm=pd.read_csv("dataset1.csv")
X_test = dfm.iloc[:,:-1]
y_test = dfm.iloc[:,-1]
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [11]:
model = SVC(kernel='linear')
model.fit(X,Y)
y_pred = model.predict(X_test)

In [12]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
from sklearn.metrics import confusion_matrix
m=confusion_matrix(y_test,y_pred)
print(m)

Accuracy: 0.56
[[27 33]
 [11 29]]


In [13]:
from sklearn.metrics import confusion_matrix
def sensitivity(y_test, y_pred):
    tp, fn, fp, tn = confusion_matrix(y_test, y_pred).ravel()
    return tp / (tp + fn)
def specificity(y_test, y_pred):
    tp, fn, fp, tn = confusion_matrix(y_test, y_pred).ravel()
    return tn / (tn + fp)
def presicion(y_test, y_pred):
    tp, fn, fp, tn = confusion_matrix(y_test, y_pred).ravel()
    return tp / (tp + fp)
def balanced_accuracy(y_test, y_pred):
    return (specificity+sensitivity)/2

In [14]:
sensitivity = sensitivity(y_test, y_pred)
print(sensitivity)
specificity=specificity(y_test, y_pred)
print(specificity)
presicion=presicion(y_test, y_pred)
print(presicion)
balanced_accuracy=balanced_accuracy(y_test, y_pred)
print(balanced_accuracy)

0.45
0.725
0.7105263157894737
0.5875


In [16]:
from sklearn.model_selection import StratifiedKFold
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, balanced_accuracy_score, confusion_matrix

strtfdKFold = StratifiedKFold(n_splits=10)
kfold = strtfdKFold.split(X, Y)

scores = []
precisions = []
specificities = []
sensitivities = []
recalls = []
balanced_accuracies = []
f1_scores = []
confusion_matrices = []

model = SVC(kernel='linear')

for k, (train, test) in enumerate(kfold):
    model.fit(X.iloc[train], Y.iloc[train])
    y_pred = model.predict(X.iloc[test])
    score = accuracy_score(Y.iloc[test], y_pred)
    precision = precision_score(Y.iloc[test], y_pred)
    recall = recall_score(Y.iloc[test], y_pred)
    balanced_accuracy = balanced_accuracy_score(Y.iloc[test], y_pred)
    f1 = f1_score(Y.iloc[test], y_pred)
    confusion = confusion_matrix(Y.iloc[test], y_pred)

    scores.append(score)
    precisions.append(precision)
    recalls.append(recall)
    balanced_accuracies.append(balanced_accuracy)
    f1_scores.append(f1)
    confusion_matrices.append(confusion)

    tn, fp, fn, tp = confusion.ravel()
    specificity = tn / (tn + fp)
    specificities.append(specificity)
    sensitivity = tp / (tp + fn)
    sensitivities.append(sensitivity)

    print('Fold: %2d, Training/Test Split Distribution: %s' % (k + 1, np.bincount(Y.iloc[train])))
    print('Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
    score, precision, specificity, sensitivity, recall))
    print('Balanced Accuracy: %.3f, F1 Score: %.3f' % (balanced_accuracy, f1))
    print('Confusion Matrix:\n', confusion)
    print('\n')

print('\n\nCross-Validation Accuracy: %.3f +/- %.3f' % (np.mean(scores), np.std(scores)))
mean_score = np.mean(scores)
mean_precision = np.mean(precisions)
mean_recall = np.mean(recalls)
mean_balanced_accuracy = np.mean(balanced_accuracies)
mean_f1 = np.mean(f1_scores)
mean_specificity = np.mean(specificities)
mean_sensitivity = np.mean(sensitivities)
mean_confusion = np.mean(confusion_matrices, axis=0)

print('Mean Accuracy: %.3f, Precision: %.3f, Specificity: %.3f, Sensitivity: %.3f, Recall: %.3f' % (
    mean_score, mean_precision, mean_specificity, mean_sensitivity, mean_recall))
print('Mean Balanced Accuracy: %.3f, F1 Score: %.3f' % (mean_balanced_accuracy, mean_f1))
print('Mean Confusion Matrix:\n', mean_confusion)
print('\n\nCross-Validation Accuracy: %.3f +/- %.3f' % (np.mean(scores), np.std(scores)))

Fold:  1, Training/Test Split Distribution: [171 189]
Accuracy: 0.475, Precision: 0.500, Specificity: 0.474, Sensitivity: 0.476, Recall: 0.476
Balanced Accuracy: 0.475, F1 Score: 0.488
Confusion Matrix:
 [[ 9 10]
 [11 10]]


Fold:  2, Training/Test Split Distribution: [171 189]
Accuracy: 0.600, Precision: 0.581, Specificity: 0.316, Sensitivity: 0.857, Recall: 0.857
Balanced Accuracy: 0.586, F1 Score: 0.692
Confusion Matrix:
 [[ 6 13]
 [ 3 18]]


Fold:  3, Training/Test Split Distribution: [171 189]
Accuracy: 0.525, Precision: 0.571, Specificity: 0.684, Sensitivity: 0.381, Recall: 0.381
Balanced Accuracy: 0.533, F1 Score: 0.457
Confusion Matrix:
 [[13  6]
 [13  8]]


Fold:  4, Training/Test Split Distribution: [171 189]
Accuracy: 0.525, Precision: 0.562, Specificity: 0.632, Sensitivity: 0.429, Recall: 0.429
Balanced Accuracy: 0.530, F1 Score: 0.486
Confusion Matrix:
 [[12  7]
 [12  9]]


Fold:  5, Training/Test Split Distribution: [171 189]
Accuracy: 0.750, Precision: 0.867, Specificity